import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModeToggle } from "@/components/shared/ThemeToggle";
import Hero from "@/components/shared/Hero";
import { SearchContextProvider } from "@/components/providers/search-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Search Stuff",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={`${inter.className} h-screen w-screen overflow-y-scroll`}
        >
          <SearchContextProvider>
            <Hero />
          </SearchContextProvider>
          {children}
          <ModeToggle />
        </body>
      </ThemeProvider>
    </html>
  );
}
